baseURL = "https://weivayn.github.io/hugo-gulp-example/"
languageCode = "en-us"
title = "This is Wei"
publishDir = "docs"


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

[params]
description = "Food, music and blog posts from Wei Vaynshteyn on social media and thisiswei.com."
author = "Wei Vaynshteyn"
