baseURL = "https://weivayn.github.io/hugo-gulp-example/"
languageCode = "en-us"
title = "Hugo Site Testing"
publishDir = "docs"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3
